class Countries {
  static String selectedCountry = '';
  static String selectedCountryCode = '';
  static Map<String, String> getCountriesAndCode() {
    Map<String, String> countriesAndCode = Map();

    countriesAndCode['India'] = 'in';
    countriesAndCode['USA'] = 'us';
    countriesAndCode['UAE'] = 'ae';
    countriesAndCode['Argentina'] = 'ar';
    countriesAndCode['Austria'] = 'au';
    countriesAndCode['Australia'] = 'at';
    countriesAndCode['Belgium'] = 'be';
    countriesAndCode['UK'] = 'gb';
    countriesAndCode['Brazil'] = 'br';
    countriesAndCode['Canada'] = 'ca';
    countriesAndCode['Switzerland'] = 'ch';
    countriesAndCode['China'] = 'cn';
    countriesAndCode['Colombia'] = 'co';
    countriesAndCode['Cuba '] = 'cu';
    countriesAndCode['Czech Republic'] = 'cz';
    countriesAndCode['Germany '] = 'de';
    countriesAndCode['Egypt '] = 'eg';
    countriesAndCode['France  '] = 'fr';
    countriesAndCode['Greece '] = 'gr';
    countriesAndCode['Hong Kong'] = 'hk';
    countriesAndCode['Hungary '] = 'hu';
    countriesAndCode['Indonesia '] = 'id';
    countriesAndCode['Ireland '] = 'ie';
    countriesAndCode['Italy '] = 'it';
    countriesAndCode['Japan '] = 'jp';
    countriesAndCode['Korea '] = 'kr';
    countriesAndCode['Lithuania '] = 'lt';
    countriesAndCode['Latvia '] = 'lv';
    countriesAndCode['Morocco '] = 'ma';
    countriesAndCode['Mexico '] = 'mx';
    countriesAndCode['Malaysia '] = 'my';
    countriesAndCode['Nigeria '] = 'ng';
    countriesAndCode['Netherlands '] = 'nl';
    countriesAndCode['Norway '] = 'no';
    countriesAndCode['New Zealand '] = 'nz';
    countriesAndCode['Philippines '] = 'ph';
    countriesAndCode['Poland '] = 'pl';
    countriesAndCode['Portugal '] = 'pt';
    countriesAndCode['Romania '] = 'ro';
    countriesAndCode['Serbia '] = 'rs';
    countriesAndCode['Russia '] = 'ru';
    countriesAndCode['Saudi Arabia'] = 'sa';
    countriesAndCode['Sweden '] = 'se';
    countriesAndCode['Singapore '] = 'sg';
    countriesAndCode['Slovenia '] = 'si';
    countriesAndCode['Slovakia '] = 'sk';
    countriesAndCode['Thailand '] = 'th';
    countriesAndCode['Turkey '] = 'tr';
    countriesAndCode['Taiwan '] = 'tw';
    countriesAndCode['Ukraine '] = 'ua';
    countriesAndCode['Venezuela '] = 've';
    countriesAndCode['South Africa'] = 'za';
    return countriesAndCode;
  }
}
